### ISSUE TITLE
Beeps on success as well as error

### ISSUE THREAD

**Issue by svileng** [charliedowler/gulp-flowtype#19]
According to documentation, it's supposed to do a console beep when there are errors, but for me it happens on every run. Using `0.4.3` and `MacOSX 10.9.5`. Any ideas?

**Comment by charliedowler** [comment]
Hmm, thats odd.

It's working fine for me, can you show me the config you're using?

Can't see anything immediately in the code that could cause it to beep when successful.

Cheers,
Charlie

**Comment by svileng** [comment]
@charliedowler

The whole app is here: https://github.com/svileng/react-es6-browserify-flowtype

I found that when I do a fresh run, if I have no errors, it doesn't beep; however, once I start getting errors, the beep never stops, even if I fix everything and it's all green. 

Thanks for having a look!

**Comment by charliedowler** [comment]
Fixed!

Thanks for the issue @svileng, this affects everyone using gulp-flowtype in a watch task.

Will publish later tonight.

**Comment by svileng** [comment]
Cheers, thanks for fixing it!
