### ISSUE TITLE
typechecking fat arrow args?

### ISSUE THREAD

**Issue by wayneseymour** [charliedowler/gulp-flowtype#27]
Should this plugin throw an "Unexpected token ," on the following:
```javascript
  return someCollection
    .reduce((inital/*: string */, obj/*: revColl */) => {
      // ...
      return // some reduction
    }, '');
```

I'm seeing an error on `initial/*: string*/,`. 
I think it wants the trailing comma to immediately follow the `initial` arg...but this only errors when using fat arrow.

Maybe this is a `react` or `babel` issue?

#### relevant package.json bits:
```json
  "devDependencies": {
    "gulp": "3.8.11",
    "gulp-babel": "5.1.0",
    "gulp-flowtype": "0.4.6",
    "gulp-react": "3.0.1"
}
```

**Comment by charliedowler** [comment]
Hi,

This shouldn't be a `gulp-flowtype` issue. This plugin is just a wrapper around the `Flow` binary, try running the binary or `babel` against your javascript and see if that helps.

Cheers,
Charlie

**Comment by wayneseymour** [comment]
Thanks

 --

*W.K. Seymour III*

Software Engineer

Intel Corporation

 High Performance Data Division
