### ISSUE TITLE
Cannot include in a pipe with a file stream

### ISSUE THREAD

**Issue by ccapndave** [charliedowler/gulp-flowtype#28]
Specifically I can't put gulp-flow after babel in a gulp stream:

```js
gulp.task('client:flow', function() {
	gulp.src(clientDir + "/src/**/*.js")
		.pipe(babel({ optional: ["runtime"], blacklist: ["flow"] }))
		.pipe(flow({
			all: false,
			weak: false,
			killFlow: false,
			beep: true,
			abort: false
		}));
});
```

This results in flow running against the un-transpiled ES6 Javascript files.  Looking at the code I see that flow works directly on `file.path`, and I get that there isn't any other obvious way to make the flow CLI with streams.  I suppose that one way to fix this is to write the transpiled files to a temporary directory, and add that directory to [include] in `.flowconfig`.  Would you say this is the best way ahead, or is there a more elegant way?

**Comment by charliedowler** [comment]
Hi,

Currently there is no stream support for `gulp-flowtype`, I'll see what I can do.

Cheers,
Charlie
