### ISSUE TITLE
Unexpected end of input

### ISSUE THREAD

**Issue by astoilkov** [charliedowler/gulp-flowtype#30]
When I run gulp-flowtype the error below is thrown. You could replicate the problem in [this repo](https://github.com/mobitroll/flow-babel-gulp).

```
[14:34:08] Using gulpfile c:\work\flow-babel-gulp-master\gulpfile.js
[14:34:08] Starting 'typecheck'...
undefined:0

^
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at c:\work\flow-babel-gulp-master\node_modules\gulp-flowtype\lib\index.js:87
:33
    at exithandler (child_process.js:758:5)
    at ChildProcess.errorhandler (child_process.js:765:5)
    at ChildProcess.emit (events.js:107:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1072:12)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
```

**Comment by charliedowler** [comment]
Hi, I'll look into this tonight. Cheers

**Comment by vakhtang** [comment]
I think it's due to stdout exceeding the max buffer size. I was able to work around this temporarily by passing a larger `maxBuffer` value to `execFile` (default is 204800).

**Comment by vakhtang** [comment]
I think it's due to stdout exceeding the max buffer size. I was able to work around this temporarily by passing a larger `maxBuffer` value to `execFile` (default is 204800). Alternatively, you could use `spawn` instead of `execFile` and stream the output.

**Comment by vakhtang** [comment]
I think it's due to stdout exceeding the max buffer size. I was able to work around this temporarily by passing a larger `maxBuffer` value to `execFile` (default is 204800). Alternatively, you could use `spawn` instead of `execFile` and stream the output.

**Comment by astoilkov** [comment]
I am closing this one. I just saw that gulp-flowtype is not supported on Windows which I was using. Sorry for the noise.
