### ISSUE TITLE
error on long startup time

### ISSUE THREAD

**Issue by FossiFoo** [charliedowler/gulp-flowtype#31]
i have a lot of node_modules (was 400MB) in my dev dependencies, that flow uncanningly parses on startup. i manually ignored a lot of them by hand in my .flowconfig and got down to 30 secs, but if status waits for the server to start, it outputs "flow server still initializing. If it was just started this can take some time. Retrying..." to stderr and gulp-flowtype fails.

ironically one of the biggest dirs is gulp-flowtype with 56MB...

**Comment by FossiFoo** [comment]
forcing "check" by using weak: true or such currently is a work around. too bad, that "node_modules" can't be ignored because of the "internal error: [...] can't find node_modules/react/package.json" error and --all will even scan through *all* files in there instead of the given input file to check. :/

gulp and the server process of flow seem not to be huge friends. that we build in a docker container (and thus kill the server every time) doesn't help either.

**Comment by charliedowler** [comment]
Hi,

Thanks for the info. I'll look into this asap.

The 56MB for gulp-flowtype is probably to do with the flow binary it downloads to run.

Cheers,
Charlie

**Comment by FossiFoo** [comment]
i went with "-lib nonExistingDir" for now.

actually, is it just me or is "--all" plain unusable? for me it always causes a full scan of node_modules/{react, react-intl,react-router,...} and does not come up at all, even calling the flow binary manually.

i wonder whether i'm doing something wrong generally.

**Comment by FossiFoo** [comment]
just to close this out, stderr output is now actually ignored by gulp-flowtype, so the above hack isn't needed any more
