### ISSUE TITLE
SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by vakhtang** [charliedowler/gulp-flowtype#32]
Getting this error:

```
[09:14:36] Starting 'typecheck'...
undefined:1
                                                                              
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at ./node_modules/gulp-flowtype/lib/index.js:87:33
    at ChildProcess.exithandler (child_process.js:758:5)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
```

Looks like it's due to stdout exceeding the max buffer size. I was able to work around this temporarily by passing a larger `maxBuffer` value to `execFile` (default is 204800). Alternatively, using `spawn` instead of `execFile` and streaming the output seems to work.

**Comment by stephanos** [comment]
I have the exact same error :(

**Comment by xelaz** [comment]
I have the same and i run it on linux (not windows). How to solve it?

```
undefined:0

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /var/projects/openreserves/node_modules/gulp-flowtype/lib/index.js:87:33
```

**Comment by vakhtang** [comment]
For a temporary workaround try the suggestions in my original comment. Update [this line in the source](https://github.com/charliedowler/gulp-flowtype/blob/master/index.js#L76) by passing a larger value of to the `maxBuffer` option ([see node API docs](https://nodejs.org/api/child_process.html#child_process_child_process_execfile_file_args_options_callback)). I think adding streaming support is the best solution here. I'll try to put in a PR when I have some time.

**Comment by xelaz** [comment]
Thx for answer, i found the problem for my self. My Debian is 32 bit and flow is available only for 64 bit system. :(

**Comment by vakhtang** [comment]
Interesting. I'm on OS X so I don't believe that's the issue.

**Comment by vakhtang** [comment]
I'm on OS X. @stephanos What OS are you using?

**Comment by xelaz** [comment]
i will try it tomorrow on my work with mac

**Comment by charliedowler** [comment]
Hi,

If you're experiencing this problem, please pull my changes down and give it a test.

Let me know if it fixed your issue.

Cheers,
Charlie

**Comment by vakhtang** [comment]
Looks like that did it, thanks.
