### ISSUE TITLE
major flow compilation speedup

### ISSUE THREAD

**Issue by opensrcken** [charliedowler/gulp-flowtype#43]
I work in a JS codebase with hundreds of files, and it is much, much faster to run flow against a top-level directory than each individual file, which is what gulp-flowtype does. In a fork, I've added support for passing a directory into `gulp.src`. I would recommend adding support for that in gulp-flowtype.

**Comment by charliedowler** [comment]
https://github.com/charliedowler/gulp-flowtype/pull/42#issuecomment-237059000
